apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "confluentinc/cp-kafka:3.3.0"
          env:
            {{- range $name, $value := .Values.envs }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.listenport }}
