version: 2

jobs:
  build:
    machine: true
    working_directory: ~/k9
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: python install -f requirements.txt
      - run:
          name: Compile proto files
          command: make compile-protos
      - run:
          name: Build scraper container image
          command: make scraper-image

