version: 2
jobs:
  "compile-protos":
    machine: true
    working_directory: ~/k9
    steps:
      - checkout
      - run:
        name: Install build dependencies
        command: python3 install -f requirements.txt
      - run:
        name: Compile proto files
        command: |
          make compile-protos
  "scraper-image":
    machine: true
    working_directory: ~/k9
    steps:
      - checkout
      - run:
        name: Build scraper container image
        command: make scraper-image

workflows:
  version: 2
  build:
    jobs:
      - "compile-protos"
      - "scraper-image":
        requires:
          - "compile-protos"
