version: 2

jobs:
  build:
    working_directory: ~/k9
    machine: true
    steps:
      - checkout
      - run:
          name: Install python build dependencies
          command: pip install --user grpcio grpcio-tools
      - run:
          name: Compile proto files
          command: make compile-protos
      - run:
          name: Build scraper container image
          command: make scraper-image

