version: 2

jobs:
  build:
    working_directory: ~/k9
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install python build dependencies
          command: pip install -f requirements.txt
      - run:
          name: Compile proto files
          command: make compile-protos
      - run:
          name: Build scraper container image
          command: make scraper-image

