apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: scylladb
          image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
          ports:
            - containerPort: {{ .Values.listenport}}
